### ISSUE TITLE
Implement Metastream as a web app

### ISSUE THREAD

**Issue by samuelmaddock** [samuelmaddock/metastream#94]
Metastream is in the process of deprecating the Electron desktop app in favor of a web app with a required browser extension. [See post on Patreon](https://www.patreon.com/posts/update-on-25999308) for details regarding reasons for this change.

In-development preview available at https://app.getmetastream.com/

![NVIDIA Share_2019-04-22_00-26-20S625](https://user-images.githubusercontent.com/1656324/56483029-51652a80-6495-11e9-821a-37740ff98c5d.png)

![NVIDIA Share_2019-04-21_23-33-10McKL](https://user-images.githubusercontent.com/1656324/56481590-dcdabd80-648d-11e9-8e95-46cc67671d84.png)

#### Todo
- [x] Compile Metastream for browsers
- [x] Host using GitHub pages
  - Work-in-progress preview available for testing at https://app.getmetastream.com/
- [x] Publish browser extension on Chrome Web Store
  - Published as [Metastream Remote](https://chrome.google.com/webstore/detail/metastream-remote/fakegmdomhmegokfomgmkbopjibonfcp)
- [x] Publish browser extension on Firefox Add-on Store
  - Published as [Metastream Remote](https://addons.mozilla.org/en-US/firefox/addon/metastream-remote/)
- [x] Re-implement subset of Electron's `<webview>` features with web extension messaging
  - This is already mostly functioning, needs some more work around history state management
- [x] Re-implement user identities with libsodium
- [x] Implement WebRTC signaling server and client for multiplayer sessions
- [x] Authenticate peers
- [x] Host backend services
  - [x] Dockerize signal server
  - [x] LetsEncrypt certs for `wss://`
  - [x] Setup WebRTC TURN server for relaying failed P2P connections (fixes #74)
- [x] Add support for site-specific scripts in extension
- [x] Cache bust service worker offline content
- [x] Network error handling
  - [x] Implement exponential backoff for host reconnecting to signal server
- [x] App update button
- [x] Install to desktop main menu button
- [x] Update git documentation, merge `webapp` branch
- [x] Support pasting session URL into join page
- [x] Change `/lobby/:id` routes to `/join/:id`
- [x] BUG: Chat box extends past bounds in Firefox
- [x] Public network testing
- [x] Change website download buttons to launch web app
- [x] Publish final update to Electron app with deprecation notice
- [x] Update browser extension description on stores

#### Post-launch
- [x] Show error when session already exists in another tab
- [x] Bind global media playback hotkeys
- [ ] Request current tab URL in Metastream when clicking extension badge
- [ ] Redesign title bar? 🤔 
- [ ] Add manual method of connecting to peer in case signal server is down 🤔 

-----

#### Features gained
- Metastream can be [installed as a desktop app](https://developers.google.com/web/progressive-web-apps/desktop) by implementing it as a Progressive Web App
- Better browser security (fixes #1)

#### Features lost
- [Discord Rich Presence](https://support.discordapp.com/hc/en-us/articles/115001557452-Game-Invites-and-Detailed-Status-Rich-Presence-) support
  - Includes custom avatars via Discord
- Distributed signalling solution ([swarm-peer-server](https://github.com/samuelmaddock/swarm-peer-server)) for WebRTC connections
- Direct IP connections
  - Will likely be replaced by a dedicated server solution eventually
- Automatic fullscreening of videos that don't fill the app's viewport
  - I have some ideas for this, but it won't fully work for videos nested in an `<iframe>`

**Comment by c-edw** [comment]
I can see this architecture being less flexible, but overall it seems like the right way to go. Massive thanks for your hard work that's going into this. I promise I'll send a few bucks your way at some point.

**Comment by LavenderTheGreat** [comment]
17/24... We are getting there slowly but surely! Well in fact, it's been going lightning speed since you started! So it's quickly but surely!
